@include('partials.hero-illu', ['figureClass' => 'hero__figure--gradient'])
@include('partials.frontpage-tabs')
@include('partials.frontpage-content')
@include('partials.content-teasers')
@include('partials.frontpage-flex')
@include('partials.frontpage-cases')